name: Validate Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Check project structure
      - name: Validate project structure
        run: |
          echo "🔍 Checking project structure..."
          node check-structure.js || true

      # 5. Check coding convention (ESLint)
      - name: Run ESLint (Coding Convention)
        run: |
          echo "🔍 Running coding convention check with ESLint..."
          npm run lint > eslint-report.txt || true
          echo "✅ Coding convention check completed."
          if grep -q 'error' eslint-report.txt; then
            echo "⚠️ Issues detected in coding convention!"
            cat eslint-report.txt
          else
            echo "🎉 No issues detected in coding convention."
          fi

      # 6. Check logic code (Jest tests)
      - name: Run Jest tests (Logic Validation)
        run: |
          echo "🔍 Running logic validation tests..."
          npm test > jest-report.txt || true
          echo "✅ Logic validation tests completed."
          if grep -q 'FAIL' jest-report.txt; then
            echo "⚠️ Issues detected in logic validation!"
            cat jest-report.txt
          else
            echo "🎉 All logic validation tests passed."
          fi

      # 7. Always mark the job as successful
      - name: Complete job
        run: echo "All checks completed."
